model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder3D.AutoencoderKL3D
  params:
    monitor: "val/rec_loss"
    embed_dim: 4
    ckpt_path: "models/first_stage_models/kl-f8/model_noD.ckpt"
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator3D
      params:
        disc_start: 5000
        ae_start: 1
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0
      checkpoint: False

lightning:
  callbacks:
    image_logger:
      target: train_video.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accelerator: "cuda"
    accumulate_grad_batches: 1
    precision: 16
